/* Three.js r160 · classic scripts，支援 file://，無外部素材請求。 */
(() => {
'use strict';
const $=id=>document.getElementById(id), E=Sokoban;
let index=0,state,history=[],sound=true,audio,topView=false,clue=-1,completed=new Set(),grabId=null,facing={x:0,y:-1},difficulty='easy',score=0,earnedSlots=new Set();
const multiplier={easy:1,normal:2,hard:3,timed:3},timedCompleted=new Set(),checkpointMilestones=new Set(),RACE_BONUS=200,select=$('levels');LEVELS.forEach((l,i)=>select.add(new Option(`題目 ${i+1}`,i)));
let renderer,scene,camera,board,playerMesh,boxMeshes=[],labels=[],goalLabels=[],currentBoardWidth=15;
let motion=null,queued=null,limbs=[],arms=[],rig,face,particles=[],goalMeshes=[],arrival=new Map(),bumpAt=0,lastTime=0,musicTimer=null,musicStep=0,speechTimer=null,cameraMotion=null,raceStartedAt=null,raceFinishedAt=null,celebrationMode='level';
let gamepadButtons=[],gamepadDirection=null,gamepadNextMove=0,gamepadIndex=null;
const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
const palette=[0xffbb47,0xff866d,0x60cbd0,0xb8a0ee,0x8bd786,0xffa1c6,0x75b9f2,0xf0a86b];
const relationColor='#e65b65',supportColor='#48ad78',relation3d=0xe65b65,support3d=0x48ad78;
function burst(x,y,color=0xffd34d,n=14){if(reduced)return;for(let i=0;i<n;i++){const m=mesh(new THREE.BoxGeometry(.09,.09,.09),color);at(m,x,y,.35);scene.add(m);particles.push({m,vx:(Math.random()-.5)*3,vy:2+Math.random()*3,vz:(Math.random()-.5)*3,life:.65+Math.random()*.3});}}
function addScore(points){if(!points)return;score+=points;$('score').textContent=`⭐ ${score} 分`;const pop=$('scorePop');pop.textContent=`+${points}`;pop.classList.remove('show');void pop.offsetWidth;pop.classList.add('show');}
function raceLimit(){return 70+LEVELS[index].words.length*5;}
function updateTimer(now=performance.now()){const el=$('timer'),timed=difficulty==='timed';el.hidden=!timed;if(!timed)return;const limit=raceLimit();if(raceStartedAt===null){el.textContent=`⏱ ${limit} 秒`;el.className='';return;}const elapsed=((raceFinishedAt??now)-raceStartedAt)/1000,remaining=Math.max(0,Math.ceil(limit-elapsed));el.textContent=elapsed<=limit?`⏱ ${remaining} 秒`:'⏱ 已超時';el.className=elapsed>limit?'overtime':remaining<=15?'urgent':'';}
function startRace(){if(difficulty==='timed'&&raceStartedAt===null){raceStartedAt=performance.now();updateTimer(raceStartedAt);}}
function cheer(){const sentence=LEVELS[index].words.join(''),finale=completed.size===LEVELS.length,checkpoint=completed.size>0&&completed.size%3===0&&!finale&&!checkpointMilestones.has(completed.size);if(checkpoint)checkpointMilestones.add(completed.size);let result='你是出色的句子搬運員！';celebrationMode=finale?'finale':checkpoint?'checkpoint':'level';if(difficulty==='timed'){raceFinishedAt=performance.now();const within=(raceFinishedAt-raceStartedAt)/1000<=raceLimit();if(within&&!timedCompleted.has(index)){timedCompleted.add(index);addScore(RACE_BONUS);result=`限時完成！額外獲得 ${RACE_BONUS} 分！`;}else if(within){result='限時完成！這一題的計時獎勵已經取得。';}else result='成功完成！已超出時限，所以沒有額外加分。';updateTimer(raceFinishedAt);}const rich=checkpoint||finale,notes=rich?[523,659,784,1047,784,988,1175,1568]:[523,659,784,1047];notes.forEach((f,i)=>setTimeout(()=>tone(f,rich ? .2 : .18),i*(rich?85:100)));for(let x=rich?1:3;x<currentBoardWidth-1;x+=rich?2:3)burst(x,3,palette[x%6],rich?28:22);$('celebrate').hidden=false;$('celebrate').querySelector('.stars').textContent=finale?'★ ★ ★ ★ ★':'★ ★ ★';$('celebrate').querySelector('h2').textContent=finale?'全部完成！':checkpoint?'恭喜完成三題！':'任務完成！';$('winResult').textContent=finale?`你完成了十五句！總分：${score} 分`:checkpoint?`你還要挑戰嗎？目前累積 ${score} 分`:result;$('winSentence').textContent=sentence;$('winNext').textContent=finale?'再玩一次':'繼續挑戰';$('winClose').textContent=rich?'休息一下':'再讀一次句子';speakSentence(sentence);}
function ensureAudio(){try{audio??=new(window.AudioContext||window.webkitAudioContext)();audio.resume();return audio;}catch{return null;}}
function chipNote(freq,duration=.1,type='square',volume=.018){if(!sound||!freq||!audio)return;const osc=audio.createOscillator(),gain=audio.createGain(),now=audio.currentTime;osc.type=type;osc.frequency.setValueAtTime(freq,now);gain.gain.setValueAtTime(volume,now);gain.gain.exponentialRampToValueAtTime(.001,now+duration);osc.connect(gain);gain.connect(audio.destination);osc.start(now);osc.stop(now+duration);}
function musicTick(){const melody=[659,784,880,784,988,880,784,659,523,659,784,880,784,659,587,659],bass=[131,165,196,165,147,175,196,175],note=melody[musicStep%melody.length];chipNote(note,.2,'square',.016);if(musicStep%2===0)chipNote(bass[(musicStep/2)%bass.length],.38,'triangle',.02);musicStep++;}
function startMusic(){if(!sound||musicTimer||!ensureAudio())return;musicTick();musicTimer=setInterval(musicTick,260);musicTimer.unref?.();}
function stopMusic(){if(musicTimer){clearInterval(musicTimer);musicTimer=null;}}
function speakSentence(sentence){clearTimeout(speechTimer);speechTimer=setTimeout(()=>{const synth=window.speechSynthesis,Utterance=window.SpeechSynthesisUtterance;if(!synth||!Utterance)return;stopMusic();synth.cancel();const utterance=new Utterance(sentence),voices=synth.getVoices?.()||[];utterance.lang='zh-HK';utterance.rate=.82;utterance.pitch=1.05;utterance.volume=1;utterance.voice=voices.find(v=>/^zh-HK/i.test(v.lang))||voices.find(v=>/^zh-(TW|Hant)/i.test(v.lang))||voices.find(v=>/^zh/i.test(v.lang))||null;const resume=()=>{if(sound)setTimeout(startMusic,350);};utterance.onend=resume;utterance.onerror=resume;synth.speak(utterance);},500);}
function tone(freq=400,duration=.09){if(!sound||!ensureAudio())return;startMusic();const osc=audio.createOscillator(),gain=audio.createGain();osc.type='square';osc.frequency.value=freq;gain.gain.setValueAtTime(.055,audio.currentTime);gain.gain.exponentialRampToValueAtTime(.001,audio.currentTime+duration);osc.connect(gain);gain.connect(audio.destination);osc.start();osc.stop(audio.currentTime+duration);}
function mesh(geometry,color){const m=new THREE.Mesh(geometry,new THREE.MeshStandardMaterial({color,roughness:.75}));m.castShadow=true;m.receiveShadow=true;return m;}
function at(obj,x,y,z=.1){obj.position.set(x-(currentBoardWidth-1)/2,z,y-4);return obj;}
function disposeTree(root){root.traverse(child=>{if(child.isMesh){child.geometry?.dispose();if(Array.isArray(child.material))child.material.forEach(item=>item.dispose());else child.material?.dispose();}});}
function buildBoard(level){currentBoardWidth=E.boardWidth(level);while(board.children.length){const child=board.children[board.children.length-1];board.remove(child);disposeTree(child);}const base=mesh(new THREE.BoxGeometry(currentBoardWidth+.6,.8,9.6),0x307e7a);base.position.y=-.55;board.add(base);const rim=mesh(new THREE.BoxGeometry(currentBoardWidth+.8,.14,9.8),0xf5bd5d);rim.position.y=-.12;board.add(rim);for(let y=0;y<E.H;y++)for(let x=0;x<currentBoardWidth;x++){const wall=!E.inside(x,y,currentBoardWidth),tile=mesh(new THREE.BoxGeometry(.98,wall?.38:.09,.98),wall?0x60a789:((x+y)%2?0xf5e9c5:0xfff2d3));board.add(at(tile,x,y,wall?.04:-.02));if(wall&&(x+y)%2===0){const cap=mesh(new THREE.BoxGeometry(.85,.07,.85),0x92c995);board.add(at(cap,x,y,.27));}}const flagX=currentBoardWidth/2-.9;for(const x of [-flagX,flagX]){const pole=mesh(new THREE.CylinderGeometry(.06,.06,2,8),0xfff0c4);pole.position.set(x,.8,-4.4);board.add(pole);const flag=mesh(new THREE.BoxGeometry(.8,.45,.05),x<0?0xff7d57:0xffd44d);flag.position.set(x+.36,1.5,-4.4);board.add(flag);}const treeX=currentBoardWidth/2+.5;for(const [x,z]of [[-treeX,-3.2],[treeX,-2],[-treeX,2.5],[treeX,3]]){const trunk=mesh(new THREE.CylinderGeometry(.13,.17,.8,7),0x946346);trunk.position.set(x,.1,z);board.add(trunk);const crown=mesh(new THREE.IcosahedronGeometry(.68,1),0x37987e);crown.position.set(x,.9,z);board.add(crown);}const dock=mesh(new THREE.BoxGeometry(currentBoardWidth-2.3,.03,1.45),0xeac989);dock.position.set(0,.055,-2);board.add(dock);resize();}
function init3d(){
 scene=new THREE.Scene();scene.background=new THREE.Color('#7ecfd1');scene.fog=new THREE.Fog(0x7ecfd1,35,65);
 renderer=new THREE.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;$('viewport').prepend(renderer.domElement);
 camera=new THREE.OrthographicCamera(-9,9,6,-6,.1,100);scene.add(new THREE.HemisphereLight(0xffffff,0x7294ae,2.5));const light=new THREE.DirectionalLight(0xffffff,3);light.position.set(-5,15,8);light.castShadow=true;light.shadow.mapSize.set(1024,1024);Object.assign(light.shadow.camera,{left:-12,right:12,top:12,bottom:-12});scene.add(light);
 board=new THREE.Group();scene.add(board);
 playerMesh=new THREE.Group();rig=new THREE.Group();playerMesh.add(rig);
 const body=mesh(new THREE.BoxGeometry(.47,.44,.35),0x1289ad);body.position.y=.48;rig.add(body);
 const badge=mesh(new THREE.BoxGeometry(.18,.14,.035),0xffd058);badge.position.set(0,.51,-.2);rig.add(badge);
 const head=mesh(new THREE.SphereGeometry(.3,20,16),0xffd7a2);head.position.y=.91;rig.add(head);
 const hat=mesh(new THREE.SphereGeometry(.33,20,12,0,Math.PI*2,0,Math.PI/2),0xffbd38);hat.position.y=1;rig.add(hat);
 const brim=mesh(new THREE.CylinderGeometry(.38,.38,.055,20),0xffc949);brim.position.y=1;rig.add(brim);
 for(const x of [-.11,.11]){const eye=mesh(new THREE.SphereGeometry(.047,12,8),0x243e45);eye.position.set(x,.91,-.278);rig.add(eye);const shine=mesh(new THREE.SphereGeometry(.015,8,6),0xffffff);shine.position.set(x-.01,.923,-.315);rig.add(shine);}
 for(const side of [-1,1]){const leg=new THREE.Group();leg.position.set(side*.15,.29,0);const boot=mesh(new THREE.BoxGeometry(.19,.23,.28),0x20556a);boot.position.set(0,-.12,-.045);leg.add(boot);rig.add(leg);limbs.push(leg);const arm=new THREE.Group();arm.position.set(side*.31,.67,0);const sleeve=mesh(new THREE.BoxGeometry(.15,.23,.16),0x16a5c0);sleeve.position.y=-.1;arm.add(sleeve);const hand=mesh(new THREE.SphereGeometry(.1,12,8),0xffd7a2);hand.position.y=-.25;arm.add(hand);rig.add(arm);arms.push(arm);}
 playerMesh.rotation.y=Math.PI;scene.add(playerMesh);
 new ResizeObserver(resize).observe($('viewport'));resize();renderer.setAnimationLoop(draw);
}
function viewPosition(isTop){return new THREE.Vector3(isTop?0:1.8,isTop?20:10.5,isTop?.01:15.5);}
function viewQuaternion(position,isTop){const helper=camera.clone();helper.up.set(0,isTop?0:1,isTop?-1:0);helper.position.copy(position);helper.lookAt(0,-.15,0);return helper.quaternion.clone();}
function settleCamera(position,isTop=topView){camera.position.copy(position);camera.quaternion.copy(viewQuaternion(position,isTop));}
function resize(){if(!renderer)return;const v=$('viewport'),w=v.clientWidth,h=v.clientHeight;renderer.setSize(w,h);const aspect=w/h,halfW=Math.max(currentBoardWidth/2+1.7,6.05*aspect),halfH=halfW/aspect;Object.assign(camera,{left:-halfW,right:halfW,top:halfH,bottom:-halfH});if(!cameraMotion)settleCamera(viewPosition(topView));camera.updateProjectionMatrix();}
function switchView(){topView=!topView;$('view').textContent=topView?'切換斜視':'切換鳥瞰';const to=viewPosition(topView),toQuaternion=viewQuaternion(to,topView);if(reduced){settleCamera(to,topView);cameraMotion=null;return;}cameraMotion={from:camera.position.clone(),to,fromQuaternion:camera.quaternion.clone(),toQuaternion,start:performance.now(),duration:1200};}
function label(text,cls=''){const el=document.createElement('span');el.className='label '+cls;el.textContent=text;$('labels').append(el);return el;}
let dynamic=[];
function rebuild(){
 if(!scene)return;dynamic.forEach(m=>{scene.remove(m);m.traverse(c=>{if(c.isMesh){c.geometry.dispose();c.material.dispose();}});});dynamic=[];$('labels').replaceChildren();labels=[];goalLabels=[];boxMeshes=[];goalMeshes=[];
 const l=LEVELS[index];E.goals(l).forEach((g,i)=>{const m=mesh(new THREE.BoxGeometry(1.04,.12,1.04),0x46b7af);at(m,g.x,g.y,.12);scene.add(m);dynamic.push(m);goalMeshes.push(m);const ring=mesh(new THREE.TorusGeometry(.39,.035,8,32),0xfff4ac);ring.rotation.x=-Math.PI/2;at(ring,g.x,g.y,.2);scene.add(ring);dynamic.push(ring);goalLabels.push({el:label(String(i+1),'goal'),x:g.x,y:g.y,id:i});});
 state.boxes.forEach(b=>{const m=new THREE.Group();const core=mesh(new THREE.BoxGeometry(.82,.58,.82),palette[b.id]);core.position.y=.31;m.add(core);m.userData.core=core;for(const z of [-.425,.425]){for(const yy of [.1,.53]){const rail=mesh(new THREE.BoxGeometry(.9,.09,.045),0x966138);rail.position.set(0,yy,z);m.add(rail);}for(const xx of [-.36,.36]){const rail=mesh(new THREE.BoxGeometry(.075,.55,.05),0xb77d40);rail.position.set(xx,.3,z);m.add(rail);}}const strap=mesh(new THREE.BoxGeometry(.12,.025,.85),0xffecab);strap.position.y=.61;m.add(strap);at(m,b.x,b.y,0);scene.add(m);dynamic.push(m);boxMeshes.push(m);labels.push(label(l.words[b.id]));});applyLearningGuides();
}
function guideFor(id){return LEVELS[index].guides?.find(g=>g.id===id);}
function applyLearningGuides(){if(!goalLabels.length)return;document.body.classList.toggle('difficulty-hard',difficulty==='hard');document.body.classList.toggle('difficulty-timed',difficulty==='timed');const easy=difficulty==='easy',normal=difficulty==='normal',strip=$('guideStrip');strip.replaceChildren();goalLabels.forEach((g,i)=>{const relation=!!guideFor(i),color=relation?relationColor:supportColor;g.el.textContent=String(i+1);g.el.className='label goal';g.el.style.color=easy?'#fffde5':'';g.el.style.backgroundColor=easy?color:'';g.el.style.borderColor=easy?color:'';goalMeshes[i].material.color.set(easy?color:0x46b7af);});state.boxes.forEach((b,i)=>{const relation=!!guideFor(b.id),show=easy||(normal&&relation),color=relation?relationColor:supportColor,solid=relation?'#ffdadd':'#d9f5e4';labels[i].style.backgroundColor=show?solid:'';labels[i].style.borderColor=show?color:'';labels[i].style.color=show?'#183f38':'';labels[i].style.opacity='1';});if(easy){strip.textContent='紅色＝關聯詞　綠色＝其他詞組';$('boardHelp').textContent='🎨 同色木箱搬到同色位置　｜　放對 +10　完成 +50';}else if(normal){strip.textContent='紅色木箱＝關聯詞';$('boardHelp').textContent='🔎 找出關聯詞及位置　｜　放對 +20　完成 +100';}else if(difficulty==='timed'){strip.textContent='第一步開始計時';$('boardHelp').textContent=`⏱ ${raceLimit()} 秒內完成額外 +${RACE_BONUS} 分　｜　超時仍可繼續`;}else{strip.textContent='';$('boardHelp').textContent='🔥 無顏色提示　｜　放對 +30　完成 +150';}}
function positionLabel(el,x,y,height){const p=new THREE.Vector3(x-(currentBoardWidth-1)/2,height,y-4).project(camera);const v=$('viewport');el.style.left=`${(p.x*.5+.5)*v.clientWidth}px`;el.style.top=`${(-p.y*.5+.5)*v.clientHeight}px`;}
function draw(now){if(!state||!playerMesh)return;const dt=Math.min((now-lastTime)/1000,.04);lastTime=now;updateTimer(now);pollGamepad(now);if(cameraMotion){const ct=Math.min((now-cameraMotion.start)/cameraMotion.duration,1),ce=ct*ct*ct*(ct*(ct*6-15)+10);camera.position.lerpVectors(cameraMotion.from,cameraMotion.to,ce);camera.quaternion.slerpQuaternions(cameraMotion.fromQuaternion,cameraMotion.toQuaternion,ce);if(ct===1)cameraMotion=null;}const active=motion,t=active?Math.min((now-active.start)/active.duration,1):1;const ease=t*t*(3-2*t);const blend=(a,b)=>a+(b-a)*ease;let px=state.player.x,py=state.player.y;if(active){px=blend(active.from.player.x,px);py=blend(active.from.player.y,py);}at(playerMesh,px,py,0);
 const stride=active?Math.sin(t*Math.PI*4):0,push=active?.pushed,pulling=active?.pulled;rig.position.y=active?(Math.abs(stride)*.055):(reduced?0:Math.sin(now*.003)*.025);rig.rotation.x=push?-.2*Math.sin(Math.PI*t):pulling?.2*Math.sin(Math.PI*t):0;rig.rotation.z=now-bumpAt<180?Math.sin((now-bumpAt)*.05)*.12:0;
 limbs.forEach((m,i)=>m.rotation.x=stride*.65*(i?1:-1));arms.forEach((m,i)=>m.rotation.x=push?1.25*Math.sin(Math.PI*Math.min(t*2,1.7)/2):pulling?-1.05:grabId!==null?-.8:stride*.5*(i?-1:1));
 const slots=E.placed(state,LEVELS[index]);state.boxes.forEach((b,i)=>{let x=b.x,y=b.y;const moving=active&&(active.from.boxes[i].x!==x||active.from.boxes[i].y!==y);if(moving){const delay=pulling?0:.13,q=Math.max(0,(t-delay)/(1-delay)),s=q*q*(3-2*q);x=active.from.boxes[i].x+(x-active.from.boxes[i].x)*s;y=active.from.boxes[i].y+(y-active.from.boxes[i].y)*s;}at(boxMeshes[i],x,y,0);const bounce=Math.max(0,1-(now-(arrival.get(b.id)||-1000))/420);boxMeshes[i].scale.set(1+bounce*.12,1-bounce*.16,1+bounce*.12);const correct=slots[b.id]===b&&(!moving||t===1),relation=!!guideFor(b.id),assisted=difficulty==='easy'||(difficulty==='normal'&&relation),boxColor=difficulty==='easy'?(relation?relation3d:support3d):difficulty==='normal'&&relation?relation3d:palette[b.id];boxMeshes[i].userData.core.material.color.setHex(boxColor);boxMeshes[i].userData.core.material.emissive.setHex(b.id===grabId?0x9c6b00:correct?0x197a4b:0x000000);boxMeshes[i].userData.core.material.emissiveIntensity=b.id===grabId?.28:correct?.2:0;labels[i].className='label'+(correct?' match':'')+(b.id===clue?' clue':'')+(b.id===grabId?' grabbed':'')+(assisted?' word-guide':'');positionLabel(labels[i],x,y,.82);});

 goalLabels.forEach((g,i)=>{positionLabel(g.el,g.x,g.y-.66,.18);g.el.style.opacity=slots[i]?'0':'1';goalMeshes[i].material.emissive.setHex(slots[i]?.id===i?0x1d7856:0x085b53);goalMeshes[i].material.emissiveIntensity=.25+(reduced?0:Math.sin(now*.003+i)*.12);});
 for(let i=particles.length-1;i>=0;i--){const p=particles[i];p.life-=dt;p.vy-=dt*7;p.m.position.x+=p.vx*dt;p.m.position.y+=p.vy*dt;p.m.position.z+=p.vz*dt;p.m.rotation.x+=dt*5;p.m.rotation.z+=dt*4;p.m.scale.setScalar(Math.min(1,p.life*3));if(p.life<=0){scene.remove(p.m);p.m.geometry.dispose();p.m.material.dispose();particles.splice(i,1);}}
 if(active&&t===1){motion=null;const previous=E.placed(active.from,LEVELS[index]);slots.forEach((b,i)=>{if(b?.id===i&&previous[i]?.id!==i){arrival.set(b.id,now);burst(b.x,b.y,0xffd65a);tone(740,.14);}});update();if(E.won(state,LEVELS[index]))cheer();else if(queued){const d=queued;queued=null;move(d);}}
 renderer.render(scene,camera);}
function update(){const l=LEVELS[index],p=E.placed(state,l),award=E.scoreAward(state,l,index,earnedSlots,completed,multiplier[difficulty]);award.slotKeys.forEach(key=>earnedSlots.add(key));if(award.completeNow){completed.add(index);updateProgress();}addScore(award.points);const win=E.won(state,l);$('steps').textContent=`${state.steps} 步`;$('undo').disabled=!history.length;
 if(win){$('message').textContent=`✓ 太好了！${l.words.join('')}　${completed.size===LEVELS.length?'全部題目完成！':''}`;}else if(p.every(Boolean)){$('message').textContent='所有詞組都到了目的地，有些位置可能需要交換。';}else{$('message').textContent=difficulty==='easy'?'先搬同色的關聯詞，再完成其他位置。':'把詞組送到上方位置。';}}
function updateProgress(){$('progress').innerHTML=LEVELS.map((_,i)=>`<span class="${i===index?'current':completed.has(i)?'done':''}">${i===index?'●':'○'}</span>`).join('');$('previousQuestion').disabled=index===0;$('nextQuestion').disabled=index===LEVELS.length-1;}
function load(i){clearTimeout(speechTimer);window.speechSynthesis?.cancel();motion=null;queued=null;grabId=null;facing={x:0,y:-1};arrival.clear();raceStartedAt=null;raceFinishedAt=null;$('celebrate').hidden=true;$('winResult').textContent='你是出色的句子搬運員！';index=i;select.value=i;state=E.start(LEVELS[i]);buildBoard(LEVELS[i]);history=[];clue=-1;syncPullButton();$('kind').textContent=LEVELS[i].kind;$('task').textContent=LEVELS[i].task;$('hint').textContent=LEVELS[i].hint;rebuild();updateTimer();updateProgress();update();}
const dirs={up:[0,-1],down:[0,1],left:[-1,0],right:[1,0]};
function gamepadButton(pad,index){return !!pad.buttons[index]?.pressed;}
function setGamepadStatus(text,connected=false){const el=$('gamepadStatus');if(el.textContent!==text)el.textContent=text;el.classList.toggle('connected',connected);}
function pollGamepad(now){const pads=globalThis.navigator?.getGamepads?.();if(!pads)return;const pad=gamepadIndex===null?[...pads].find(Boolean):pads[gamepadIndex];if(!pad){gamepadIndex=null;gamepadButtons=[];gamepadDirection=null;setGamepadStatus('🎮 按手掣任意鍵連接');return;}gamepadIndex=pad.index;setGamepadStatus('🎮 已連接｜搖桿移動　A拉箱　B復原　X視角　Y重設　LT/RT轉題',true);const ax=pad.axes[0]||0,ay=pad.axes[1]||0,direction=gamepadButton(pad,12)||ay<-.55?'up':gamepadButton(pad,13)||ay>.55?'down':gamepadButton(pad,14)||ax<-.55?'left':gamepadButton(pad,15)||ax>.55?'right':null;if(direction!==gamepadDirection){gamepadDirection=direction;if(direction){move(direction);gamepadNextMove=now+320;}}else if(direction&&now>=gamepadNextMove){move(direction);gamepadNextMove=now+150;}const pressed=pad.buttons.map(button=>button.pressed);if(pressed[0]&&!gamepadButtons[0]){$('celebrate').hidden?toggleGrab():$('winNext').click();}if(pressed[1]&&!gamepadButtons[1]){$('celebrate').hidden?undo():$('winClose').click();}if(pressed[2]&&!gamepadButtons[2])switchView();if(pressed[3]&&!gamepadButtons[3])load(index);if(pressed[6]&&!gamepadButtons[6])load(Math.max(0,index-1));if(pressed[7]&&!gamepadButtons[7])load(Math.min(LEVELS.length-1,index+1));gamepadButtons=pressed;}
function syncPullButton(){const on=grabId!==null;$('pull').classList.toggle('active',on);$('pull').setAttribute('aria-pressed',String(on));$('pull').innerHTML=on?'✋ 放開木箱 <small>G</small>':'👐 拉住木箱 <small>G</small>';}
function toggleGrab(){if(motion)return;if(grabId!==null){grabId=null;syncPullButton();$('message').textContent='放手！現在可以繼續推箱。';tone(300);return;}const movable=b=>!E.locked(state,b,LEVELS[index]),ahead=state.boxes.find(b=>movable(b)&&b.x===state.player.x+facing.x&&b.y===state.player.y+facing.y),near=ahead||state.boxes.find(b=>movable(b)&&Math.abs(b.x-state.player.x)+Math.abs(b.y-state.player.y)===1);if(!near){bumpAt=performance.now();tone(150,.07);$('message').textContent='要先行到未鎖定的木箱旁邊，才可以拉住它！';return;}grabId=near.id;syncPullButton();$('message').textContent=`抓實「${LEVELS[index].words[grabId]}」！用方向鍵拖它轉彎，完成後再按一次放手。`;tone(560,.15);}
function move(dir){if(motion){queued=dir;return;}if(E.won(state,LEVELS[index]))return;const [dx,dy]=dirs[dir];facing={x:dx,y:dy};const old=state,next=grabId===null?E.move(state,dx,dy,LEVELS[index]):E.pull(state,grabId,dx,dy,LEVELS[index]);playerMesh&&(playerMesh.rotation.y=Math.atan2(-dx,-dy));if(!next){bumpAt=performance.now();tone(150,.06);$('message').textContent=grabId===null?'哎呀，推不動！放對的木箱已經鎖定。':'拉唔郁！放對的木箱已經鎖定。';return;}startRace();history.push(old);state=next;const movedBox=old.boxes.some((b,i)=>b.x!==state.boxes[i].x||b.y!==state.boxes[i].y),pulled=grabId!==null;motion={from:old,start:performance.now(),duration:reduced?65:movedBox?300:190,pushed:movedBox&&!pulled,pulled};$('undo').disabled=false;$('steps').textContent=`${state.steps} 步`;$('message').textContent=pulled?'拉住啦！可以繼續轉方向拖行。':movedBox?'嘿咻！把詞組送到它的位置。':'走到箱子旁邊，可以推，也可以按「拉住木箱」！';tone(pulled?430:movedBox?380:240,movedBox?.12:.045);if(movedBox)burst(old.player.x,old.player.y,0xf6e4bd,5);}
function undo(){if(!history.length)return;motion=null;queued=null;grabId=null;syncPullButton();$('celebrate').hidden=true;state=history.pop();update();tone(330);}
document.addEventListener('keydown',e=>{if(/INPUT|SELECT|TEXTAREA/.test(e.target.tagName))return;const keys={ArrowUp:'up',w:'up',ArrowDown:'down',s:'down',ArrowLeft:'left',a:'left',ArrowRight:'right',d:'right'};const k=e.key.length===1?e.key.toLowerCase():e.key;if(keys[k]){e.preventDefault();move(keys[k]);}else if(k==='g'){e.preventDefault();toggleGrab();}else if(k==='u'||k==='z'){e.preventDefault();undo();}else if(k==='r'){e.preventDefault();load(index);}});
let repeatDelay,repeatTimer;function stop(){clearTimeout(repeatDelay);clearInterval(repeatTimer);}document.querySelectorAll('[data-dir]').forEach(b=>{b.addEventListener('pointerdown',e=>{e.preventDefault();stop();b.setPointerCapture(e.pointerId);move(b.dataset.dir);repeatDelay=setTimeout(()=>repeatTimer=setInterval(()=>move(b.dataset.dir),150),350);});b.addEventListener('pointerup',stop);b.addEventListener('pointercancel',stop);b.addEventListener('lostpointercapture',stop);b.addEventListener('click',e=>{if(e.detail===0)move(b.dataset.dir);});});window.addEventListener('blur',stop);document.addEventListener('visibilitychange',stop);
window.addEventListener('gamepadconnected',event=>{gamepadIndex=event.gamepad.index;setGamepadStatus('🎮 已連接｜搖桿移動　A拉箱　B復原　X視角　Y重設　LT/RT轉題',true);});window.addEventListener('gamepaddisconnected',event=>{if(gamepadIndex===event.gamepad.index){gamepadIndex=null;gamepadButtons=[];gamepadDirection=null;setGamepadStatus('🎮 手掣已斷線，按任意鍵重連');}});
document.querySelectorAll('[data-difficulty]').forEach(button=>button.onclick=()=>{if(difficulty===button.dataset.difficulty)return;difficulty=button.dataset.difficulty;document.querySelectorAll('[data-difficulty]').forEach(b=>b.classList.toggle('active',b===button));load(index);});
 $('previousQuestion').onclick=()=>load(Math.max(0,index-1));$('nextQuestion').onclick=()=>load(Math.min(LEVELS.length-1,index+1));
 $('pull').onclick=toggleGrab;$('undo').onclick=undo;$('reset').onclick=()=>{stop();load(index);};select.onchange=()=>{stop();load(Number(select.value));};$('sound').onclick=()=>{sound=!sound;if(sound){$('sound').textContent='♫ 音樂及音效開';tone();}else{$('sound').textContent='♫ 音樂及音效關';stopMusic();audio?.suspend();}$('sound').setAttribute('aria-pressed',sound);};$('view').onclick=switchView;$('hintButton').onclick=()=>{const p=E.placed(state,LEVELS[index]);clue=p.findIndex((b,i)=>b?.id!==i);$('hint').textContent=clue<0?'已經全部正確，讀出整句吧！':`第 ${clue+1} 格放「${LEVELS[index].words[clue]}」。找找有金色外框的箱子，推或拉到正確位置。`;tone(620);};
 $('winNext').onclick=()=>load(celebrationMode==='finale'?0:(index+1)%LEVELS.length);$('winClose').onclick=()=>{if(celebrationMode==='level'){speakSentence(LEVELS[index].words.join(''));return;}$('celebrate').hidden=true;stopMusic();};
 try{init3d();}catch(err){$('error').hidden=false;console.error(err);}load(0);
})();














